# Generated by Django 5.0 on 2024-03-13 23:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Status Trabajo')),
            ],
            options={
                'verbose_name': 'Status Trabajo',
                'verbose_name_plural': 'Status Trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=150, unique=True, verbose_name='Número de Orden')),
                ('fecha_trabajo', models.DateField(default=datetime.datetime.now)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=150, verbose_name='Teléfono')),
                ('vehiculo', models.CharField(max_length=150, verbose_name='Vehículo/Color')),
                ('detalle', models.CharField(max_length=500, verbose_name='Detalle')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.statustrabajo', verbose_name='Status Trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-fecha_trabajo'],
            },
        ),
    ]
