# Generated by Django 5.0 on 2024-03-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_statustrabajo_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
