# Generated by Django 5.0 on 2024-03-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_trabajo_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proveedor',
            field=models.CharField(default=0.0, max_length=150, verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
    ]
