# Generated by Django 5.0 on 2024-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_product_proveedor_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='0000', max_length=30, unique=True, verbose_name='SKU'),
        ),
    ]
