# Generated by Django 5.0 on 2024-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='taller/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
