# Generated by Django 5.0 on 2024-03-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_trabajo_options_alter_trabajo_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número de Orden'),
        ),
    ]
