# Generated by Django 5.0 on 2024-03-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_trabajo_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
