# Generated by Django 5.0 on 2024-03-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_trabajo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['-fecha_trabajo'], 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
