# Generated by Django 5.0 on 2024-04-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_trabajo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['-id'], 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
