# Generated by Django 5.0 on 2024-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_alter_trabajo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de Orden'),
        ),
    ]
