# Generated by Django 5.0 on 2024-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_alter_trabajo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telefono')),
                ('vehiculo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vehiculo')),
            ],
            options={
                'verbose_name': 'ClienteTaller',
                'verbose_name_plural': 'ClientesTaller',
                'ordering': ['id'],
            },
        ),
    ]
