# Generated by Django 5.0 on 2024-05-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_clientetrabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientetrabajo',
            old_name='name',
            new_name='names',
        ),
    ]
