# Generated by Django 5.0 on 2024-05-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_remove_trabajo_apellido_remove_trabajo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['id'], 'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
