# Generated by Django 5.0 on 2024-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_trabajo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
