# Generated by Django 5.0 on 2024-05-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_ticket_card_ticket_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
