# Generated by Django 5.0 on 2024-05-26 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_sale_card_sale_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrircaja',
            name='fecha_apertura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cerrarcaja',
            name='fecha_cierre',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
