# Generated by Django 5.0 on 2024-05-28 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_alter_abrircaja_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_cash',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
