# Generated by Django 5.0 on 2024-06-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_alter_ticket_date_cash_alter_ticket_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastocaja',
            options={'ordering': ['-id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
    ]
