# Generated by Django 5.0 on 2024-06-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_alter_gastocaja_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastocaja',
            options={'ordering': ['-fecha_gasto'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
    ]
