# Generated by Django 5.0 on 2024-06-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skuprove',
            field=models.CharField(default='0000', max_length=30, verbose_name='SKU Proveedor'),
        ),
    ]
