# Generated by Django 5.0 on 2024-06-28 23:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_product_skuprove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='apellido',
            field=models.CharField(default=0, max_length=150, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='nombre',
            field=models.CharField(default=0.0, max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='telefono',
            field=models.CharField(default=0.0, max_length=150, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='vehiculo',
            field=models.CharField(default=0.0, max_length=150, verbose_name='Vehículo/Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='detalle',
            field=models.CharField(max_length=500, verbose_name='Detalle'),
        ),
        migrations.CreateModel(
            name='Trabajo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número de Orden')),
                ('fecha_trabajo', models.DateField(default=datetime.datetime.now)),
                ('detalle', models.CharField(max_length=700, verbose_name='Detalle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='taller/%Y/%m/%d', verbose_name='Imagen')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.clientetrabajo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.statustrabajo', verbose_name='Status Trabajo')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['-id'],
            },
        ),
    ]
