# Generated by Django 5.0 on 2025-01-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_alter_trabajo2_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastocaja',
            options={'ordering': ['-id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
    ]
