# Generated by Django 5.0 on 2025-01-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_alter_gastocaja_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastocaja',
            name='usuario',
        ),
    ]
