# Generated by Django 5.0 on 2025-01-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_remove_gastocaja_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo2',
            name='image',
        ),
    ]
