# Generated by Django 5.0 on 2025-01-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_remove_trabajo2_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo2',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número de Orden'),
        ),
    ]
