# Generated by Django 5.0 on 2025-01-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_alter_trabajo2_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo2',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Orden'),
        ),
    ]
